---
title: "Matrix Builder scMilvus"
author: "Cory Henn"
format: html
editor: visual
---


```{r}
library(Seurat)
library(ggplot2)
library(tidyverse)
library(Matrix)
library(reticulate)
#library(umap)
#library(tsne)
library(HGNChelper)
library(ggraph)
library(ggrastr)
library(patchwork)
#library(scCATCH)
```

```{r}
# Load necessary libraries
library(Matrix)

# Set file paths
matrix_file <- "fil_a_matrix.mtx"
features_file <- "fil_a_features.tsv"
cells_file <- "fil_a_barcodes.csv"
output_file <- "output_matrix.csv"  # Define the output file path

# Read matrix data from Matrix Market file
matrix_data <- readMM(matrix_file)

# Read feature names from TSV file
feature_names <- read.table(features_file, header = FALSE, sep = "\t")[, 2]

# Read cell barcodes from CSV file
cell_barcodes <- read.csv(cells_file, header = FALSE)[, 1]

# Create the matrix
matrix <- matrix(matrix_data, nrow = length(cell_barcodes), ncol = length(feature_names))

# Set row and column names
rownames(matrix) <- cell_barcodes
colnames(matrix) <- feature_names

# Print the matrix
print(matrix)

# Export the matrix to a CSV file
write.csv(matrix, file = output_file, row.names = TRUE)  # Set row.names = FALSE if you don't want row names in the CSV file

# Print a message indicating the export is complete
cat("Matrix has been exported to", output_file, "\n")
```

